# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SampleZ <- function(y, z_hat, z) {
    invisible(.Call(`_FABIO_SampleZ`, y, z_hat, z))
}

CalcPosterior <- function(cHyp, ng_test, yty, Xgamma, s_size, XtX, Xty, Xb, beta) {
    .Call(`_FABIO_CalcPosterior`, cHyp, ng_test, yty, Xgamma, s_size, XtX, Xty, Xb, beta)
}

CalcXtX <- function(X, y, s_size, XtX, Xty) {
    invisible(.Call(`_FABIO_CalcXtX`, X, y, s_size, XtX, Xty))
}

CalcCC_PVEnZ <- function(Xb, ni_test, cHyp, z_hat) {
    invisible(.Call(`_FABIO_CalcCC_PVEnZ`, Xb, ni_test, cHyp, z_hat))
}

ProposeH <- function(cHyp_old, rep, h_max, h_min, h_scale) {
    .Call(`_FABIO_ProposeH`, cHyp_old, rep, h_max, h_min, h_scale)
}

ProposePi <- function(cHyp_old, cHyp_new, rep, logp_max, logp_min, logp_scale, beta_a, beta_b) {
    .Call(`_FABIO_ProposePi`, cHyp_old, cHyp_new, rep, logp_max, logp_min, logp_scale, beta_a, beta_b)
}

mcmc_iter <- function(total_step, w_step, r_pace, w_pace, n_mh, ng_test, ni_test, h_max, h_min, h_scale, g_max, g_min, logp_max, logp_min, logp_scale, beta_a, beta_b, y, z_hat, z, rank_old, beta_old, beta_new, Xtz_old, Xtz_new, Xb_old, Xb_new, p_gamma, pos_vec, cHyp_old, X, Xgamma_old, Xgamma_new, XtX_old, XtX_new, Result_hyp, Result_gamma, beta_g, display_progress = TRUE) {
    .Call(`_FABIO_mcmc_iter`, total_step, w_step, r_pace, w_pace, n_mh, ng_test, ni_test, h_max, h_min, h_scale, g_max, g_min, logp_max, logp_min, logp_scale, beta_a, beta_b, y, z_hat, z, rank_old, beta_old, beta_new, Xtz_old, Xtz_new, Xb_old, Xb_new, p_gamma, pos_vec, cHyp_old, X, Xgamma_old, Xgamma_new, XtX_old, XtX_new, Result_hyp, Result_gamma, beta_g, display_progress)
}

